/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ShaktiCareContact {
  'id' : bigint,
  'relation' : string,
  'userId' : Principal,
  'name' : string,
  'isDefault' : boolean,
  'phone' : string,
}
export interface ShaktiCareDietEntry {
  'id' : bigint,
  'title' : string,
  'createdBy' : [] | [Principal],
  'description' : string,
  'isPreloaded' : boolean,
  'category' : string,
}
export interface ShaktiCareFirstAidEntry {
  'id' : bigint,
  'createdBy' : [] | [Principal],
  'isPreloaded' : boolean,
  'steps' : Array<string>,
  'situation' : string,
}
export interface ShaktiCareLocalService {
  'id' : bigint,
  'name' : string,
  'type' : string,
  'district' : string,
  'address' : string,
  'phone' : string,
}
export interface ShaktiCareUserProfile {
  'age' : bigint,
  'name' : string,
  'healthCondition' : string,
}
export interface ShaktiCareWorkoutEntry {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'difficulty' : string,
  'description' : string,
  'category' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDietEntry' : ActorMethod<
    [string, string, string, boolean, [] | [Principal]],
    bigint
  >,
  'createFirstAidEntry' : ActorMethod<
    [string, Array<string>, boolean, [] | [Principal]],
    bigint
  >,
  'createLocalService' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createWorkoutEntry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [ShaktiCareUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<ShaktiCareContact>>,
  'getDietEntriesByCategory' : ActorMethod<
    [string],
    Array<ShaktiCareDietEntry>
  >,
  'getFirstAidEntries' : ActorMethod<[], Array<ShaktiCareFirstAidEntry>>,
  'getServicesByType' : ActorMethod<[string], Array<ShaktiCareLocalService>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [ShaktiCareUserProfile]>,
  'getWorkoutsByCategory' : ActorMethod<
    [string],
    Array<ShaktiCareWorkoutEntry>
  >,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[ShaktiCareUserProfile], undefined>,
  'updateUserProfile' : ActorMethod<[string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];