/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShaktiCareUserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'healthCondition' : IDL.Text,
});
export const ShaktiCareContact = IDL.Record({
  'id' : IDL.Nat,
  'relation' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
});
export const ShaktiCareDietEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdBy' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'isPreloaded' : IDL.Bool,
  'category' : IDL.Text,
});
export const ShaktiCareFirstAidEntry = IDL.Record({
  'id' : IDL.Nat,
  'createdBy' : IDL.Opt(IDL.Principal),
  'isPreloaded' : IDL.Bool,
  'steps' : IDL.Vec(IDL.Text),
  'situation' : IDL.Text,
});
export const ShaktiCareLocalService = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'district' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ShaktiCareWorkoutEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDietEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'createFirstAidEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'createLocalService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createWorkoutEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(ShaktiCareUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ShaktiCareContact)], ['query']),
  'getDietEntriesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShaktiCareDietEntry)],
      ['query'],
    ),
  'getFirstAidEntries' : IDL.Func(
      [],
      [IDL.Vec(ShaktiCareFirstAidEntry)],
      ['query'],
    ),
  'getServicesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShaktiCareLocalService)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ShaktiCareUserProfile)],
      ['query'],
    ),
  'getWorkoutsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShaktiCareWorkoutEntry)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([ShaktiCareUserProfile], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShaktiCareUserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'healthCondition' : IDL.Text,
  });
  const ShaktiCareContact = IDL.Record({
    'id' : IDL.Nat,
    'relation' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const ShaktiCareDietEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdBy' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'isPreloaded' : IDL.Bool,
    'category' : IDL.Text,
  });
  const ShaktiCareFirstAidEntry = IDL.Record({
    'id' : IDL.Nat,
    'createdBy' : IDL.Opt(IDL.Principal),
    'isPreloaded' : IDL.Bool,
    'steps' : IDL.Vec(IDL.Text),
    'situation' : IDL.Text,
  });
  const ShaktiCareLocalService = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'district' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ShaktiCareWorkoutEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDietEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'createFirstAidEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'createLocalService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createWorkoutEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(ShaktiCareUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(ShaktiCareContact)], ['query']),
    'getDietEntriesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShaktiCareDietEntry)],
        ['query'],
      ),
    'getFirstAidEntries' : IDL.Func(
        [],
        [IDL.Vec(ShaktiCareFirstAidEntry)],
        ['query'],
      ),
    'getServicesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShaktiCareLocalService)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ShaktiCareUserProfile)],
        ['query'],
      ),
    'getWorkoutsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShaktiCareWorkoutEntry)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([ShaktiCareUserProfile], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };